### ISSUE TITLE
Is there any working tag of this package?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.googleauthenticator#10]
Currently master branch seems to have some issues to me and I'm not being able to make it work.

**Comment by barseghyanartur** [comment]
@hvelarde:

0.2.5 worked for sure, as I have been using it in production for some time.

**Comment by lukasgraf** [comment]
I gotta say, I haven't been using this package for a while now anymore (switched to doing 2FA outside Plone). However, at the time where I was still using it, my latest commit was what worked for me back then.

(In the end I went with something else because I got the impression that PAS pretty much inherently expects authentication to be performed in one request/response cycle, and cramming two-step-authentication in there felt a bit like a hack)

**Comment by hvelarde** [comment]
@lukasgraf what are you using for 2FA?

**Comment by barseghyanartur** [comment]
@lukasgraf, @hvelarde:

Until now, I have been using collective.smsauthenticator (which was made based on this package) in production for a couple of years. The client I have been using it for, passed a couple of independent security audits. 

The reason we have moved to SMS from GA is that client requested something simpler than that (smartphone was an assumption which was not always present for all employees).

**Comment by lukasgraf** [comment]
@hvelarde Ruby CASino with a custom TOTP plugin: http://casino.rbcas.com/

**Comment by hvelarde** [comment]
one more question: do you guys think is possible to add the **collective** account as owner of this package in PyPI?

**Comment by barseghyanartur** [comment]
@hvelarde:

Done for:

- collective.smsauthenticator
- collective.googleauthenticator
- collective.twittercards

I assume, that only highly responsible people have access to that one.

**Comment by hvelarde** [comment]
@barseghyanartur do you mind to add it as **owner** and not as **maintainer** only?

**Comment by barseghyanartur** [comment]
@hvelarde:

Done.

Also for:

- eea.facetednavigationtaxonomiccheckbox
